FROM ubuntu:21.10

RUN apt-get update && apt-get upgrade -y
RUN apt-get install mingw-w64-x86-64-dev g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix binutils-mingw-w64-x86-64 build-essential cmake git wget -y
RUN wget https://github.com/conan-io/conan/releases/latest/download/conan-ubuntu-64.deb
RUN dpkg -i conan-ubuntu-64.deb
RUN mkdir /test
WORKDIR /test
RUN git init
RUN git submodule add https://github.com/jtv/libpqxx.git libs/libpqxx
RUN wget https://gist.github.com/DerKnerd/ab506480e32aab0d2b3e564fa2e67906/raw/0be5039549e71f5080ef15a7173730af0dd1f222/CMakeLists.txt
RUN wget https://gist.github.com/DerKnerd/ab506480e32aab0d2b3e564fa2e67906/raw/0be5039549e71f5080ef15a7173730af0dd1f222/conan.cmake
RUN wget https://gist.github.com/DerKnerd/ab506480e32aab0d2b3e564fa2e67906/raw/0be5039549e71f5080ef15a7173730af0dd1f222/linux_to_win64.conan
RUN wget https://gist.github.com/DerKnerd/ab506480e32aab0d2b3e564fa2e67906/raw/0be5039549e71f5080ef15a7173730af0dd1f222/main.cpp
RUN wget https://gist.github.com/DerKnerd/ab506480e32aab0d2b3e564fa2e67906/raw/0be5039549e71f5080ef15a7173730af0dd1f222/mingw.cmake

RUN cmake -DCMAKE_TOOLCHAIN_FILE=mingw.cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build/